### ISSUE TITLE
Move Anemometer to separate library

### ISSUE THREAD

**Issue by thijstriemstra** [ClassicDIY/SkyeTracker#22]
I'd like to use the Anemometer class in other non-SkyeTracker projects as well. Can it be moved to a separate repository/project so it can be used by other Arduino projects? Feel free to add me as a team member, I can help out with this.

**Comment by thijstriemstra** [comment]
thanks @graham22, I'm now a member. Maybe you can import the classes into a new repository (with vscode/platformio type structure), something like https://github.com/SkyeTracker/anemometer?

**Comment by thijstriemstra** [comment]
And what do you suggest to call the main repository, something like SkyeTracker-core? I think the Android code should also have it's own repository. Would be cool if the new repositories get their code imported in a such a way that the git log history is retained.

**Comment by graham22** [comment]
I'm not sure I want to split everything up,  I have Jonas working on the CAD drawings and I have the hardware PCBs  where would these go?

**Comment by thijstriemstra** [comment]
Alright, I see your point. I would move all documentation related things like that in a `doc` dir in root of repository. Perhaps we can use sphinx documentation tool to generate some nice documentation and move away from the wiki.

ps. I can also make the anemometer repository but then the code will not contributed to you in the git history, that's why I'm asking you to add the intial classes.

**Comment by graham22** [comment]
Make a copy of the library for your use
