### ISSUE TITLE
Zeit Verschiebung germany

### ISSUE THREAD

**Issue by jens-software** [ClassicDIY/SkyeTracker#28]
Die Zeit stimmt um 2 Std nicht

**Comment by graham22** [comment]
The time is in UTC, German time is +2 hours

**Comment by jens-software** [comment]
Wo muss das den alles geändert werden

**Comment by graham22** [comment]
I'm not sure if I understand the issue
You have to set the UTC date/time using the android app along with the lat/lon so that it can calculate the sun's elevation and azimuth

**Comment by jens-software** [comment]
Hi
I mean that the time is not right, if it is 4 p.M. It shows 2 p.M. In the app.
I.

**Comment by graham22** [comment]
Fixed datetime display on info tab (release 2.5.1) published to google play, thanks
