### ISSUE TITLE
Loosing settings

### ISSUE THREAD

**Issue by catalincre** [ClassicDIY/SkyeTracker#42]
Hi, great work. I have a problem with my installation, if the esp32 is loosing power the settings are also lost. Thats an issue in a remote area with no constant power. Is there a way to make the settings permanent in the code like those for wifi?

**Comment by graham22** [comment]
The settings are stored in non-volatile ram and should persist through a power cycle. The default setting will load on the following conditions;
1. if the factory reset pin is low (Pin 4)
2. if the checksum value is wrong indicating corrupt data.
3. The NVRam can't be loaded.

if you compile the code with "-D APP_LOG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG" in platform.ini, it will log to a serial monitor. This may help determine the issue.
The relevant code is in code/ESP32/src/Configuration.cpp -> void Configuration::Load()

**Comment by catalincre** [comment]
Sorry, the settings are lost on two instance every time the esp is loosing power, after the new security update on samsung, can't open the app anymore on two phones, a s23 ultra and a flip 3.

**Comment by graham22** [comment]
I have updated the google app to API 33 so it should work on most new phones.

**Comment by catalincre** [comment]
It works now, thx. It can be closed.
